### ISSUE TITLE
Nueva función: delete_entities

### ISSUE THREAD

**Issue by fgalan** [telefonicasc/etl-framework#14]
En ocasiones, una ETL puede necesitar borrar  entidades existetentes. La librería debería incluir una función para ello, pe. delete_entities

Los parámetros a dar esa función creo que podrían ser los mismos que para get_entities_page(), salvo los relacionado con paginación que no tienen sentido aquí. Incluyento también los 4 nuevos que se mencionan en https://github.com/telefonicasc/etl-framework/issues/13

La API del CB no permite deletes con filtros y demás, pero la librería podría encargarse de consultar primero todas las entidades y aplicarlos. Una posibilidad menos ambiciosa sería que la función expuesta por la librería fuese similar al borrado que permite el Context Broker (basicamente, basado en una lista concreta de entidades), pero creo que searía menos potente.

**Comment by arcosa** [comment]
Podemos hacer una función de borrado que (delete_entities):
- Reciba los mismos parámetros que el get_entities_page. Que pase los parámetros al get_entities_page para que recoja las entidades que concuerden los con filtros definidos y estas serían las entidades candidatas a eliminar.
- Para cada una de las entidades candidatas que lance un borrado por "entityid" y "entitytype" (para evitar problemas de duplicados de entityid con entitytypes diferentes).

Lo único, es que a diferencia del script de borrado que hemos usado, No habría "verificación" de las entidades a borrar, para que se use como un proceso desatendido.

Ahora mismo tenemos el get_entities_page, pero si implementamos la recogida sin paginación definida (con paginación interna -  https://github.com/telefonicasc/etl-framework/issues/5), en plan "get_entites", podría ser esta que la que podríamos usar en vez de get_entities_page. Pero eso implica, tener lista la issue https://github.com/telefonicasc/etl-framework/issues/5 antes.

**Comment by fgalan** [comment]
> Para cada una de las entidades candidatas que lance un borrado por "entityid" y "entitytype" (para evitar problemas de duplicados de entityid con entitytypes diferentes).

El borrado no lo haría una a una con `DELETE /v2/entities/{id}` sino en un `POST /v2/op/update` con `"actionType": "delete"`. Solo hace falta un objeto con `id` y `type` que identifique la entidad, no hace falta incluir ningún atributo. Aplicaría también la lógica de limitacion de tamaño de bloque que tenemos en send_batch (parece improbable, pero si hay muchas entidades a borrar igual sobrepasa el tamaño permitido a un solo `POST /v2/op/update`).

Por otra parte en la docu avisaría que el borrado no es "transaccional". Por ejemplo, si entre que recupero las entidades página a página y hago el borrado ocurre la mala suerte de que alguien crea una nueva entidad que cumple el filtrado pero cae en una página ya recorrida, esta igual se escapa al borrado.

> Lo único, es que a diferencia del script de borrado que hemos usado, No habría "verificación" de las entidades a borrar, para que se use como un proceso desatendido.

Esto no lo acabo de entender...

**Comment by fgalan** [comment]
PR #26
