### ISSUE TITLE
Paginación y recogida de datos de CB con CPr

### ISSUE THREAD

**Issue by arcosa** [telefonicasc/etl-framework#38]
Se ha detectado un funcionamiento anómalo en el mecanismo de paginación que se usa en la librería, para los casos en que el Context Broker tenga Context Providers registrados.

Para evitar ese problema, se va incorporar el parámetro skipForwarding en las recogidas de datos. Se añadirá un parámetro opcional skipForwarding, que por defecto está a true. Cuando está a true añade a las peticiones /v2/entities el options=skipForwarding  y en false, no añade nada. De este modo, por defecto conseguimos que no influya los Context Providers registrados en la recogida de entidades.

**Comment by fgalan** [comment]
Issue raiz en el repositorio del Context Broker: https://github.com/telefonicaid/fiware-orion/issues/847

**Comment by fgalan** [comment]
Una posibilidad sería implementar un mecanismos genérico de paso de opciones en cualquier de las operaciones del CB:

* send_batch
* get_entities_page
* get_entities
* delete_entities

Seria algo así:

> :param opcional options: Array de opciones que se incluirán en la llamada al CB. Por defecto, no se incluye ninguna opción.

En este caso concreto, el usuario utilizaria `options: [ "skipForwarding" ]` a la hora de llamar get_entities.

El único problema que veo es que "pise" lo que el usuario ponga ahí con el uso de options que hace la lógica actual. Creo que solo afecta a este punto:

https://github.com/telefonicasc/etl-framework/blob/64c16c733f86bf565f9dba2f0ba5d82974dda34d/python-lib/tc_etl_lib/tc_etl_lib/cb.py#L354

Habría que definir un criterio en caso de colisión y creo que debería de tomar prioridad el parámetro. Es decir:

> :param opcional options: Array de opciones que se incluirán en la llamada al CB. En el caso de que haya colisión entre las opciones de este array y las que use la librería por defecto, toma preferencia las que se definan en este parámetro. Por defecto, no se incluye ninguna opción.

**Comment by fgalan** [comment]
PR https://github.com/telefonicasc/etl-framework/pull/39
