### ISSUE TITLE
Evolucion de get_entities sin paginación

### ISSUE THREAD

**Issue by fgalan** [telefonicasc/etl-framework#5]
La verión 0.1.0 incorpora una función get_entities_page() que permite obtener páginas de entidades desde el CB.

El problema es que el usuario es quien tiene que gestionar el recorrido paginado de las entidades (ver ejemplo "Recogida de todos los datos de tipo SupplyPoint con paginación").

Estaría bien liberar al usuario de este tema, de forma que la librería se encargue por debajo de ir pidiendo páginas. Para ello podemos ver si existe algún tipo de patrón iterador fácil de aplicar en Python.

**Comment by fgalan** [comment]
@arcosa dice:

> Entiendo que el uso sería para los casos de que el usuario quiera recoger todos los datos y se enfrenta a la limitación de los 1.000 registros del cb, que tenga un:
> 
> ```python
> data = get_entities_iterator(orderBy='id', type='SupplyPoint') 
> ```
> 
> que internamente, haga un iterador, usando una paginación interna, usando el offset = 0, limit = 1000 y aplicando los argumentos que haya podido definir y vaya acumulando los resultados en una única estructura, preferiblemente igual que la que retorna get_entities_page, que será la que retorne finalmente la función get_entitites_iterator cuando haya recogido todos los resultados.

**Comment by fgalan** [comment]
> ¿La idea es que ese `data` fuese un array con todas la entidades de tipo `SupplyPoint`, no?

**Comment by fgalan** [comment]
> Disponemos de una implementación con paginación interna, en el script de `synctoassets`. Se puede hacer una función similar, con parámetros similares a los de get_entities_page (excluyendo el offset). Que use internamente el get_entities_page y el cálculo del paginación internamente, pasándole los filtros que se hayan definido.
> 
> como nombre, tal vez le pondría: get_entities
> 
> el mecanismo que utiliza, es ir solicitando entidades al CB con cierto limit, mientras va incrementando el offset en función de la paginación interna y en el momento que el cb no retorne más entidades, da por completado la lectura de todas las entidades. El limit lo dejaría como configurable, porque en ocasiones el ampliar el tamaño de entidades a recibir en cada solicitud, puede mejorar el rendimiento frente a generar un volumen muy elevado de solicitudes.

Me parece buena estrategia para implementarlo. Y entiendo que se confirma lo que antes preguntaba, que todas las entidades acaban devueltas en un array.

Mi único "concern" aquí es que resulte un array monstruoso. En un caso hipótetico, imagina que tenemos un millón de entidades, cada una con del orden de 100 atributos. El array será monstruoso, no sé si tanto como para tumbar el proceso Python en el que se genere. Pero supongo en todo caso que eso es problema del usuario, que está loco haciendo una operación como esa sin filtrar. Como mucho pondría un aviso en la documentación (si es que mi concern tiene sentido y no es solo paranoia :)

**Comment by arcosa** [comment]
Entiendo la inquietud, se podría poner un limite de tamaño de recogida de datos por defecto, lo suficientemente alto para que en la mayoría de casos no se tenga que especificar.. por ejemplo 9999 entidades en el array.

Que por defecto vaya a recoger todas las entidades y que pare en el momento que se supere ese tamaño. Y que sea una parámetro configurable (opcional) en el get_entities, de modo que fuerzas a quien usa la función a establecer un limite bajo su responsabilidad.

```python
#Recoge todos los escenarios (máximo 9999) 
json = cbm.get_entities(auth=auth, subservice=<subservicio>, orderBy='id', type='Scenario')

#Recoge todos los escenarios, incrementando el límite máximo a 1.000.000
json = cbm.get_entities(auth=auth, subservice=<subservicio>, orderBy='id', type='Scenario', result_limit = 1000000)
```

**Comment by fgalan** [comment]
No lo compliquemos. Dejemos de momento libertad completa y si eso se vuelve un problema en algún momento, introducimos un mecanismo como el que comentas. Igual no llegamos a ver nunca un get_entities de un millón de entidades :)

**Comment by fgalan** [comment]
> No lo compliquemos. Dejemos de momento libertad completa y si eso se vuelve un problema en algún momento, introducimos un mecanismo como el que comentas. Igual no llegamos a ver nunca un get_entities de un millón de entidades :)

Aunque si mi comentario llega tarde y ya lo tienes implementado en PR #20 :) déjalo entonces

**Comment by fgalan** [comment]
PR  [#6](https://github.com/telefonicasc/etl-framework/issues/6)
