### ISSUE TITLE
escapar texto para usar como ID de entidad

### ISSUE THREAD

**Issue by rg2011** [telefonicasc/etl-framework#54]
En el contexto de https://github.com/telefonicasc/webusage-vertical/pull/15#discussion_r1091579111 se comentó la conveniencia de añadir a la librería una función para *escapar* una cadena de texto, de forma que el resultado se pueda usar como ID de una entidad NGSI.

La función eliminaría o reemplazaría todos los caracteres prohibidos en un ID de entidad, especificados aquí: https://github.com/telefonicaid/fiware-orion/blob/master/doc/manuals/orion-api.md#general-syntax-restrictions

Aquí hay un snippet del tipo de función que estaríamos hablando: https://gist.github.com/rg2011/641703016c4f1951913826984b447b58

Una vez tuviéramos esta función, habría que modificar las siguientes ETLs para usarla:

- [ETL Google Analytcis de webusage-vertical](https://github.com/telefonicasc/webusage-vertical/pull/15)

**Comment by fgalan** [comment]
Fixed by PR https://github.com/telefonicasc/etl-framework/pull/61
