### ISSUE TITLE
Warning SSL en ejecución de ETLs, Librería `http.Session`

### ISSUE THREAD

**Issue by kevinacuna** [telefonicasc/etl-framework#76]
En el issue https://github.com/telefonicasc/sc_smartregionmurcia-project/issues/258 se ha detectado un Warning en la ejecución de la ETL `AEMET` del vertical `environment`

Se ha investigado y la ETL está funcional, el log muestra un warning que no afecta al envío de información al CB. El error proviene del uso de la librería interna `http.Sessions()`, la cual no cierra la conexión creada en el fichero https://github.com/telefonicasc/etl-framework/blob/master/python-lib/tc_etl_lib/tc_etl_lib/cb.py (line:343)

Se recomienda el uso de `finally` para cerrar el la conexión creada.

### Error
```log
self.__send_batch(auth=auth, service=service, subservice=subservice, entities=entitiesToSend, actionType=actionType, options=options)
ResourceWarning: Enable tracemalloc to get the object allocation traceback
/opt/etls/sc_smartregionmurcia/workspace/SmartRegionMurcia/PRO/aemet_integration/etls/aemet_integration/venv/lib64/python3.8/site-packages/tc_etl_lib/cb.py:277: ResourceWarning: unclosed <ssl.SSLSocket fd=3, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=6, laddr=('81.45.58.71', 54636), raddr=('81.45.14.55', 10027)>
```

_**Nota:**_ Replicar este error en LAB es imposible, pues es un error de certificado que solo ocurre en LIVE

**Comment by fgalan** [comment]
PR #79
